# Chạy Redis trên port 6379
port 6379

# Cho phép truy cập từ ngoài container
bind 0.0.0.0

# Bật bảo mật (optional)
requirepass 123456

# Giới hạn bộ nhớ (optional)
maxmemory 100mb
maxmemory-policy allkeys-lru